pipeline {
    agent {
        label 'slave'
    }    
    stages {
        stage('Build') {
            steps {
                sh 'node --version' 
                echo "Get working directory"
                sh 'pwd'
            }
        }
    }
}
